config/routes.rb
Rails.application.routes.draw do

  resources :meals
  get 'welcome' => 'welcome#index'
  get 'welcome/about' => 'welcome#about', as: :about

  post 'welcome/login' => 'user#login', as: :login
  post 'welcome/signup' => 'user#signup', as: :signup
  get 'welcome/logout' => 'user#logout', as: :user_logout
  get 'user' => 'user#show', as: :user
  get 'matches' => 'messages#matches', as: :matches

  get 'search' => 'search#index', as: :search
  get 'search/results' => 'search#results'
  post 'search/candidates' => 'search#searchForNearbyBusinesses'
  post 'search/sendMessage' => 'search#sendMessage'
  post 'search/accept' => 'search#accept'
  post 'search/reject' => 'search#reject'

  get 'messages' => 'messages#index'
  get 'profile' => 'profile#index'
  get 'profile/edit' => 'profile#edit'
  post 'profile/edit' => 'profile#submit', as: :profile_submit
  resources :messages
  root 'welcome#index'

end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id          :integer          not null, primary key
#  content     :string(255)
#  sender_id   :string(255)
#  receiver_id :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  read        :boolean
#  match_id    :integer
#

class Message < ActiveRecord::Base
	belongs_to :match
  #validates_presence_of :body, :recepient
  #validates length: { minimum: 3, maximum: 35 }
  #validates :body, length: { minimum: 3, maximum: 1000 }



  #validates_presence_of :subject, :body, :recepient
  #validates :subject, length: { minimum: 3, maximum: 35 }
  #validates :body, length: { minimum: 3, maximum: 1000 }
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @user = User.where(locu_str_id: session['current_locu_id']).first
    @messages = Message.where('receiver_id = :locu_id OR sender_id = :locu_id', locu_id: params["locu_id"]).order("created_at desc")
    messages_to_update = @messages.where("receiver_id = :id", id: session['current_locu_id'])
    messages_to_update.update_all(:read => true)
    respond_to do |format|
      format.html
      format.json { render json: @messages }
    end
  end

  def matches
    @matches = Match.where('receiver_id = :locu_id OR sender_id = :locu_id', locu_id: session['current_locu_id']).where(accepted: true)
  end

  def show 
    @message = Message.find(params[:id])
    @user = User.where(locu_str_id: session['current_locu_id']).first
    if (@user.locu_str_id == @message.sender_id) || (@user.locu_str_id == @message.receiver_id)
    else
      respond_to do |format|
        format.html { redirect_to :action => :index, notice: 'No message found' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.create(params.require(:message).permit(:receiver_id, :content))
    @message.sender_id = session['current_locu_id']
    @message.save

    respond_to do |format|
      if @message.save
        flash[:notice] = 'Message has been sent.'

        format.html { redirect_to messages_path(locu_id: @message.receiver_id) }
        format.json { render json: @messages }
      else
        format.html { redirect_to new_message_path(@message) }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end
end

app/helpers/message_helper.rb
module MessageHelper
  def marked_as_read(message)
    if @message.read != 1 
      @message.read = 1
      @message.save 
    end
  end
end

app/views/messages/_form.html.erb
<%= form_for @message=Message.new() do |form| %>
  <% if @message.errors.any? %>
    <div class = "alert alert-danger" role="alert">
      <div><b>Error(s)</b></div>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%=msg%></li>
      <% end %> 
    </div> 
  <% end %>
  <h3><%= 'To: ' + User.get_name(params[:locu_id]) %></h3><br/>
  <%= form.hidden_field :receiver_id, { value: params[:locu_id]} %>
  <%= form.label :content, 'New Message' %><br/>
  <%= form.text_area :content, size:'50x4', width:'300px' %><br/><br/>
  <%= form.submit 'Send message', :class => 'btn btn-primary' %>
<% end %>

app/views/messages/_message.html.erb
<% #unless Message.where(sender_id: @user.locu_str_id).where(receiver_id: message.sender_id).empty? %>
  <% if message.receiver_id == @user.locu_str_id || message.sender_id == @user.locu_str_id %>
  <table class="table">
    <tr>
      <td class="narrow">
        <a href="#message_content"><%= User.get_name(message.sender_id) %></a>:
      </td>
      <td>
        <%= message.content %>
      </td>
      <td>
        <%= message.created_at %>
      </td>
    </tr>
  </table>
  <% #end %>
<% end %>

app/views/messages/_new.html.erb
<div id="newMessage">
  <%= render 'form' %>
  <%= link_to 'Back', matches_path %>
</div>

app/views/messages/_sent.html.erb
<% @messages.each do |m| %>
<% if m.sender_id == @user.locu_str_id %>
<table class="table">
  <tr>
    <td>
      <%= link_to User.get_name(m.sender_id), message_path(m) %>
      <% if m.read %>
        [read by user]
      <% end %>
    </td>
    <td>
      <%= User.get_name(m.receiver_id) %>
    </td>
    <td><%= m.created_at %></td>
    <td><%= link_to 'Delete Message', m, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
</table>
<% end %>
<% end %>

app/views/messages/_show.html.erb
<div id="readMessage">
<h3>Message</h3>
<table class = "table">
  <tr>
    <td>From</td>
    <td>To</td>
    <td>Date</td>
  </tr>
  <tr>
    <td><strong><%= User.get_name(@message.sender_id) %></strong></td>
    <td><strong><%= User.get_name(@message.receiver_id) %></strong></td>
    <td><strong><%= @message.created_at %></strong></td>
  </tr>
</table>

<p><%= @message.content %></p>
<%= link_to 'Back', messages_path %>
</div>

app/views/messages/index.html.erb
<div class="container">
  <div class="row">
    <h2><%= link_to 'Your Matches', matches_path %></h2>
  </div>
</div>

  <div class="container">
  <div class="row" id="inboxMessages">
    <h2>Chat with: <%= User.get_name(params['locu_id']) %></h2>
    <div id="messages">
      <%= render @messages %> 
    </div>
    <div>
      <%= render new_message_path %>
    </div>
  </div>
</div>

<!--<div class="container">
  <div class="row" id="sentMessages">
    <h2>Sent Messages</h2>
    <table class="table">
      <tr>
        <td>From</td>
        <td>To</td>
        <td>Date</td>
        <td>Delete?</td>
      </tr>
    </table>
    <div id="messages">
      <%= render 'messages/sent' %> 
    </div>
  </div>
</div>-->

app/views/messages/matches.html.erb
<div class="container">
  <div class="row">
    <h2> Your Matches! </h2>
  </div>
  <div class="row">
    <table class="table">
      <% @matches.each do |match| %>
      <tr>
        <td>
          <% if match.sender_id == session['current_locu_id'] %>
            <%= link_to User.get_name(match.receiver_id), messages_path(locu_id: match.receiver_id) %> 
          <% else %>
            <%= link_to User.get_name(match.sender_id), messages_path(locu_id: match.sender_id) %>
          <% end %>
          <span style="padding-left:3%">Unread Messages: <%= match.unread_messages_for_user(session['current_locu_id']).count %></span>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/messages/new.html.erb
    <%= render 'messages/new' %>

app/views/messages/show.html.erb
    <%= render 'messages/show' %>

<% marked_as_read(@message) %>