config/routes.rb
Rails.application.routes.draw do

  resources :meals
  get 'welcome' => 'welcome#index'
  get 'welcome/about' => 'welcome#about', as: :about

  post 'welcome/login' => 'user#login', as: :login
  post 'welcome/signup' => 'user#signup', as: :signup
  get 'welcome/logout' => 'user#logout', as: :user_logout
  get 'user' => 'user#show', as: :user
  get 'matches' => 'messages#matches', as: :matches

  get 'search' => 'search#index', as: :search
  get 'search/results' => 'search#results'
  post 'search/candidates' => 'search#searchForNearbyBusinesses'
  post 'search/sendMessage' => 'search#sendMessage'
  post 'search/accept' => 'search#accept'
  post 'search/reject' => 'search#reject'

  get 'messages' => 'messages#index'
  get 'profile' => 'profile#index'
  get 'profile/edit' => 'profile#edit'
  post 'profile/edit' => 'profile#submit', as: :profile_submit
  resources :messages
  root 'welcome#index'

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  helper_method :searchForNearbyBusinesses

  @candidates = []

  def findBusinesses(candidates)
    my_id = session["current_locu_id"]
    candidates.each do |candidate|
      candidate["confidence"] = 0.0
      if !Match.where(sender_id: candidate["locu_id"], receiver_id: my_id,
                      accepted: false, selling: true).empty?
        candidate["confidence"] = 1.0
      else
        user = User.where(locu_str_id: candidate["locu_id"]).first
        me = User.where(locu_str_id: my_id).first
        categories = User.get_categories(candidate["locu_id"], candidate["categories"])
        if user and me.needs and categories
          needs = me.needs.split(', ')
          categories = categories.split(', ')
          if needs.empty?
            candidate["confidence"] = 0.5
          else
            number_of_matches = (needs & categories).length
            candidate["confidence"] = number_of_matches.to_f / needs.length
          end
        end
      end
    end
    return candidates.sort { |c1, c2| c2["confidence"] <=> c1["confidence"] }
  end

  def findCustomers(candidates)
    my_id = session["current_locu_id"]
    candidates.each do |candidate|
      candidate["confidence"] = 0.0
      if !Match.where(sender_id: candidate["locu_id"], receiver_id: my_id,
                      accepted: false, selling: false).empty?
        candidate["confidence"] = 1.0
      else
        user = User.where(locu_str_id: candidate["locu_id"]).first
        me = User.where(locu_str_id: my_id).first
        if user and me.categories and user.needs
          needs = user.needs.split(', ')
          categories = me.categories.split(', ')
          if needs.empty?
            candidate["confidence"] = 0.5
          else
            number_of_matches = (needs & categories).length
            candidate["confidence"] = number_of_matches / needs.length
          end
        end
      end
    end
    return candidates.sort { |c1, c2| c2["confidence"] <=> c1["confidence"] }
  end

  def searchForNearbyBusinesses(distance=1000, category=nil)
    business = searchForBusiness(session["current_locu_id"])
    coordinates = business["location"]["geo"]["coordinates"]
    fields = ["name", "location", "contact", "categories", "media"]
    queries = [
      {
        location: {
          geo: {
            "$in_lat_lng_radius" => [coordinates[1], coordinates[0], distance]
          }
        }
      }
    ]

    results = searchLocu(fields, queries)["venues"]
    # Filter out my own business
    results.select! {|result| result["locu_id"] != session["current_locu_id"]}
    if params[:type] == 'customer'
      @candidates = findCustomers(results)
    else
      @candidates = findBusinesses(results)
    end
    render 'results'
  end

  def accept
    user_id = session["current_locu_id"]
    candidate_id = params[:candidate_id]
    selling = (params[:type] == 'customer')

    matches = Match.where(sender_id: candidate_id, receiver_id: user_id)
    if matches.empty?
      # Create a match if no match already exists
      match = Match.new
      match.sender_id = user_id
      match.receiver_id = candidate_id
      match.accepted = false
      match.selling = selling
      match.save

    elsif (matches.first.selling != selling) || (!matches.first.selling && !selling)
      # Otherwise, if a match exists, only accept it if
      # I'm buying and she's selling, or I'm selling and she's buying
      # or if we are both buying
      match = matches.first
      match.accepted = true
      match.save

      # Autogenerate two messages
      message = Message.new
      message.sender_id = match.sender_id
      message.receiver_id = match.receiver_id
      message.content = "You've been matched!"
      message.save

      message = Message.new
      message.sender_id = match.receiver_id
      message.receiver_id = match.sender_id
      message.content = "You've been matched!"
      message.save

      render :js => "window.location = '#{messages_path}?locu_id=#{candidate_id}'"
      return
    end
    render :nothing => true
  end

  def index
    @candidates = []
  end
  
  def results
    if @candidates.empty?
      redirect_to search_path
    end
  end

end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_contact.html.erb
<%= form_tag search_sendMessage_path, html: {class: "form-horizontal"} do %>

  <%= text_area_tag "content", nil, :placeholder=>"Enter message", :cols=>5, :class=>"form-control"%>

  <%= hidden_field_tag "receiver_id" %>

  <%= submit_tag "Chat", class: "btn btn-large btn-primary" %>

<% end %>

app/views/search/index.html.erb
<div class="container">

  <div class="row page-header">
    <div class="col-md-4 col-md-offset-2 centered">
      <h2>Search other businesses</h2>
      <%= button_to "GET OUT THERE", search_candidates_path(:type=>"business"), {:class=>"btn-large btn search-box godaddy-orange", :id=>"wider"} %>
    </div>
    <div class="col-md-4 centered">
      <h2>Find customers</h2>
        <%= button_to "GET MATCHED", search_candidates_path(:type=>"customer"), :class=>"search-box godaddy-green", :id=>"wider" %>
    </div>
  </div>
</div>

app/views/search/needs.html.erb
<%= @locu_categories_hash %>

<script>
	function createOptionsRecursively( data, container ) {
	    var option = {category: $('<option>'+ data.category.title +'</option>')};
	    container.push(option);
	    if (data.children && data.children != []) {
	        option.children = [];
	        for (item in data.children)
	            createOptionsRecursively( data.children[item], option.children );
	    }
	}

	var items = [];
	var url = "https://raw.githubusercontent.com/Yelp/yelp-api/master/category_lists/en/category.json";
	$.getJSON(url, function(data){
		$.each(data, function( k, v, s ) {
		    createOptionsRecursively( data[k], items );
		});
		console.log(items);
	});
	
</script>

app/views/search/results.html.erb
<div id="matches-carousel" class="carousel slide">
  <div class="carousel-inner">

    <% @candidates.each_with_index do |candidate, index| %>
    <% if index == 0 %>
      <div class="item active" id="<%=candidate['locu_id']%>">
    <% else %>
      <div class="item" id="<%=candidate['locu_id']%>">
    <% end %>

      <!-- image logic -->
      <% if candidate["media"] and candidate["media"]["cover_photo"] %>
        <%= image_tag candidate["media"]["cover_photo"], :class => "cover-photo"%>
      <% else %>
        <% if candidate["categories"] %>
          <%= image_tag seedImage(candidate["categories"][0]["name"], "large"), :class => "cover-photo" %>
        <% else %>
          <%= image_tag "carousel-placeholder"+(1+rand(4)).to_s+".jpg", :class => "cover-photo"%>
        <% end %>
      <% end %>
      <!-- end image logic -->

      <div class="carousel-caption">
        <h2><%=candidate["name"] %></h2>
        <h2 style="display: none"><%=candidate["locu_id"] %></h2>
        <% if candidate["website_url"] %>
          <%=link_to "website", candidate["website_url"]%>
        <% end %>
        <% if candidate["contact"] && candidate["contact"]["email"] %>
          <%=link_to "Email: "+candidate["contact"]["email"], "mailto:"+candidate["contact"]["email"], style:"color:white;" %>
        <% end %>
        <ul>
          <li><%=candidate["location"]["address1"] %></li>
          <% if candidate["location"]["address2"] %>
            <li><%=candidate["location"]["address2"] %></li>
          <% end %>
          <% if candidate["location"]["address3"] %>
            <li><%=candidate["location"]["address3"] %></li>
          <% end %>
          <% if candidate["location"]["locality"] && candidate["location"]["region"] && candidate["location"]["postal_code"] %>
            <li><%= candidate["location"]["locality"] +", "+candidate["location"]["region"] + " "+candidate["location"]["postal_code"] %></li>
          <% end %>
        </ul>
        <p class="lead"><%= candidate["description"] %></p>
      </div>
    </div>
    <% end %>

  </div>

</div>
    <button class="btn btn-danger" id="reject">REJECT</button>
    <button class="btn btn-success" id="accept">ACCEPT</button>

<script>
$(function() {

  $('#reject').click(function() {
    $('#accept').attr('disabled', true);
    $('#reject').attr('disabled', true);
    $('#matches-carousel').carousel('next');
  });

  $('#accept').click(function() {
    $('#accept').attr('disabled', true);
    $('#reject').attr('disabled', true);
    var candidate_id = $('#matches-carousel .active').prop('id');

    $.ajax({
      url: "accept",
      type: "POST",
      data: {type: '<%= params[:type] %>',
             candidate_id: candidate_id},
      success: function() {
        $('#matches-carousel').carousel('next');
      }
    });
  });

  $('#matches-carousel').carousel({
    interval: false,
    wrap: false
  });
  $('#matches-carousel').on('slid.bs.carousel', function() {
    $('#accept').removeAttr('disabled');
    $('#reject').removeAttr('disabled');
  });

});
</script>