config/routes.rb
Rails.application.routes.draw do

  resources :meals
  get 'welcome' => 'welcome#index'
  get 'welcome/about' => 'welcome#about', as: :about

  post 'welcome/login' => 'user#login', as: :login
  post 'welcome/signup' => 'user#signup', as: :signup
  get 'welcome/logout' => 'user#logout', as: :user_logout
  get 'user' => 'user#show', as: :user
  get 'matches' => 'messages#matches', as: :matches

  get 'search' => 'search#index', as: :search
  get 'search/results' => 'search#results'
  post 'search/candidates' => 'search#searchForNearbyBusinesses'
  post 'search/sendMessage' => 'search#sendMessage'
  post 'search/accept' => 'search#accept'
  post 'search/reject' => 'search#reject'

  get 'messages' => 'messages#index'
  get 'profile' => 'profile#index'
  get 'profile/edit' => 'profile#edit'
  post 'profile/edit' => 'profile#submit', as: :profile_submit
  resources :messages
  root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Get Matched</title>
  <%= favicon_link_tag       '/favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
          <%=link_to "Get Matched", root_url, class: "navbar-brand" %>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li>
              <%= link_to "Home", "/" %>
            </li>
            <li>
              <%= link_to "About", about_path %>
            </li>
          </ul>

          <% if logged_in? %>
            <% if Match.total_unread_messages(session['current_locu_id']) != 0 %>
              <ul class="nav navbar-nav navbar-left" style="text-align: center;margin-left:13%;background-color:#DEBD00;">
                <li><%= link_to "Messages (" + Match.total_unread_messages(session['current_locu_id']).to_s + " unread)", matches_path %></li>
              </ul>
            <% else %>
              <ul class="nav navbar-nav navbar-left" style="text-align: center;margin-left:13%;">
                <li><%= link_to "Messages (0)", matches_path %></li>
              </ul>
            <% end %>
          <% end %>

          <ul class="nav navbar-nav navbar-right">
          <% if logged_in?%>
            <li><%= link_to "Welcome, " + User.get_name(session['current_locu_id']), profile_path%></li>
            <li><%= link_to "Profile", profile_path, :id=>"messages"%></li>
            <li><%= link_to "Log out", user_logout_path, :id=>"logout"%></li>
          <% else %>
            <li><%= link_to "Log In", "#", :id=>"login"%></li>
            <li><%= link_to "Sign Up", "#", :id=>"signup"%></li>
          <% end %>
          </ul>
        </div>
    </div>
</div>

<% unless flash.blank? %>
<div class="container">
  <% flash.each do |type, message| %>
    <div class="alert <%= bootstrap_class_for(type) %> fade in">
      <button class="close" data-dismiss="alert">×</button>
      <%= message %>
    </div>
  <% end %>
</div>
<% end %>

<%= yield %>

</body>
</html>